name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn

      - run: yarn install
      - run: yarn lint:hbs
      - run: yarn lint:js

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn

      - run: yarn install
      - run: yarn test:ember

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: ['lint', 'test']

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.16
          - ember-lts-3.24
          - ember-lts-3.28
          # temporarily disabled because they are currently failing
          # - ember-release
          # - ember-beta
          # - ember-canary
          - ember-default-with-jquery

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: yarn

      - run: yarn
      - run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
